//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMapEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringtrans {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringtrans() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSMapEditor.Resources.stringtrans", typeof(stringtrans).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 查找... 的本地化字符串。
        /// </summary>
        internal static string BrowseButtonText {
            get {
                return ResourceManager.GetString("BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新地图 的本地化字符串。
        /// </summary>
        internal static string CreateNewMapButtonText {
            get {
                return ResourceManager.GetString("CreateNewMapButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者,你愿意在下面选择地图 的本地化字符串。
        /// </summary>
        internal static string DirectoryListingText {
            get {
                return ResourceManager.GetString("DirectoryListingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件加载出错 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageLoadingFile {
            get {
                return ResourceManager.GetString("ErrorMessageLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏目录: 的本地化字符串。
        /// </summary>
        internal static string GameDirectoryLabelText {
            get {
                return ResourceManager.GetString("GameDirectoryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏路径[指向特定的可执行文件 eg:YRCLient.exe] 的本地化字符串。
        /// </summary>
        internal static string GameDirectoryText {
            get {
                return ResourceManager.GetString("GameDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 并不是合法的游戏可运行文件 请尝试修改后重试 的本地化字符串。
        /// </summary>
        internal static string InvalidFileSelected_Message {
            get {
                return ResourceManager.GetString("InvalidFileSelected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的游戏文件路径 的本地化字符串。
        /// </summary>
        internal static string InvalidFileSelected_Title {
            get {
                return ResourceManager.GetString("InvalidFileSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 {0} 文件或任何文件名包含 &apos;Client&apos; 的可执行文件 的本地化字符串。
        /// </summary>
        internal static string InvalidFileSelectedMD_Message {
            get {
                return ResourceManager.GetString("InvalidFileSelectedMD_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的文件选择 的本地化字符串。
        /// </summary>
        internal static string InvalidFileSelectedMD_Title {
            get {
                return ResourceManager.GetString("InvalidFileSelectedMD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图路径存在问题，请尝试修改后重试。 的本地化字符串。
        /// </summary>
        internal static string InvalidMapPath_Message {
            get {
                return ResourceManager.GetString("InvalidMapPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误地图路径 的本地化字符串。
        /// </summary>
        internal static string InvalidMapPath_Title {
            get {
                return ResourceManager.GetString("InvalidMapPath_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入 的本地化字符串。
        /// </summary>
        internal static string LoadButtonText {
            get {
                return ResourceManager.GetString("LoadButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        internal static string LoadingMessageBoxText {
            get {
                return ResourceManager.GetString("LoadingMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可加载的地图文件地址 [可指定为相对地址] 的本地化字符串。
        /// </summary>
        internal static string MapPathLabelText {
            get {
                return ResourceManager.GetString("MapPathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图宽度加高度不能超过 {0} 单元格 的本地化字符串。
        /// </summary>
        internal static string MapTooLarge_Message {
            get {
                return ResourceManager.GetString("MapTooLarge_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图太大 的本地化字符串。
        /// </summary>
        internal static string MapTooLarge_Title {
            get {
                return ResourceManager.GetString("MapTooLarge_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图高度不能超过 {0} 单元格 的本地化字符串。
        /// </summary>
        internal static string MapTooLong_Message {
            get {
                return ResourceManager.GetString("MapTooLong_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图太长 的本地化字符串。
        /// </summary>
        internal static string MapTooLong_Title {
            get {
                return ResourceManager.GetString("MapTooLong_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图宽度必须至少是 {0} 单元格 的本地化字符串。
        /// </summary>
        internal static string MapTooNarrow_Message {
            get {
                return ResourceManager.GetString("MapTooNarrow_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图太窄 的本地化字符串。
        /// </summary>
        internal static string MapTooNarrow_Title {
            get {
                return ResourceManager.GetString("MapTooNarrow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图高度必须至少是 {0} 单元格 的本地化字符串。
        /// </summary>
        internal static string MapTooSmall_Message {
            get {
                return ResourceManager.GetString("MapTooSmall_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图太小 的本地化字符串。
        /// </summary>
        internal static string MapTooSmall_Title {
            get {
                return ResourceManager.GetString("MapTooSmall_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图宽度不能超过 {0} 单元格 的本地化字符串。
        /// </summary>
        internal static string MapTooWide_Message {
            get {
                return ResourceManager.GetString("MapTooWide_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图太宽 的本地化字符串。
        /// </summary>
        internal static string MapTooWide_Title {
            get {
                return ResourceManager.GetString("MapTooWide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染比例:  的本地化字符串。
        /// </summary>
        internal static string RenderScaleLabelText {
            get {
                return ResourceManager.GetString("RenderScaleLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚动速度: 的本地化字符串。
        /// </summary>
        internal static string ScrollRateLabelText {
            get {
                return ResourceManager.GetString("ScrollRateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置项 的本地化字符串。
        /// </summary>
        internal static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以无边框模式启动 的本地化字符串。
        /// </summary>
        internal static string StartInBorderlessModeText {
            get {
                return ResourceManager.GetString("StartInBorderlessModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本编辑器路径 的本地化字符串。
        /// </summary>
        internal static string TextEditorPathLabelText {
            get {
                return ResourceManager.GetString("TextEditorPathLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题:  的本地化字符串。
        /// </summary>
        internal static string ThemeLabelText {
            get {
                return ResourceManager.GetString("ThemeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用粗体字体 的本地化字符串。
        /// </summary>
        internal static string UseBoldFontLabelText {
            get {
                return ResourceManager.GetString("UseBoldFontLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WAE CHN Version Beta 的本地化字符串。
        /// </summary>
        internal static string windowTitle {
            get {
                return ResourceManager.GetString("windowTitle", resourceCulture);
            }
        }
    }
}
